apiVersion: v1
kind: Service
metadata:
  name: admin-client
  labels:
    app: admin-client
spec:
  type: ClusterIP
  selector:
    app: admin-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
