apiVersion: apps/v1
kind: Deployment
metadata:
  name: webshop-api
spec:
  template:
    spec:
      containers:
        - name: webshop-api
          # Pin your prod tag here (change during releases)
          image: eliasdb/webshop-api:v2.0.2
          env:
            - name: APP_ENV
              value: 'production'
            - name: APP_DEBUG
              value: 'false'
            - name: APP_URL
              value: 'https://api.eliasdebock.com'

            - name: DB_CONNECTION
              value: 'pgsql'
            - name: DB_HOST
              value: 'postgres-service-prod'
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-prod
                  key: POSTGRES_USER
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-prod
                  key: WEBSHOP_DB
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-prod
                  key: POSTGRES_PASSWORD

            - name: KEYCLOAK_JWKS_URL
              value: 'https://app.eliasdebock.com/keycloak/realms/EDB-PROD/protocol/openid-connect/certs'

            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: meilisearch-secret-prod
                  key: MEILI_MASTER_KEY
            - name: MEILISEARCH_KEY
              valueFrom:
                secretKeyRef:
                  name: meilisearch-secret-prod
                  key: MEILI_MASTER_KEY

            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret-prod
                  key: OPENAI_API_KEY

            - name: STRIPE_PUBLIC
              valueFrom:
                secretKeyRef:
                  name: stripe-secret-prod
                  key: STRIPE_PUBLIC
            - name: STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: stripe-secret-prod
                  key: STRIPE_SECRET
