---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: postgres-data-staging
spec:
    capacity:
        storage: 40Gi # Match the size of your staging volume
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: /mnt/volume # Mount point of your Hetzner staging volume
