apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-client-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # Track the image and let Image Updater update staging tags
    argocd-image-updater.argoproj.io/image-list: platform-client=eliasdb/edb
    argocd-image-updater.argoproj.io/platform-client.allow-tags: regexp:^pr-\d+-staging$
    argocd-image-updater.argoproj.io/platform-client.update-strategy: newest-build
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: apps
  source:
    repoURL: https://github.com/Eliasdb/eDB.git
    targetRevision: dev
    path: k8s/product/platform-client/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - PruneLast=true
