apiVersion: v1
kind: Service
metadata:
    name: admin-app-staging-service
    namespace: default
    labels:
        app: admin-app
spec:
    type: ClusterIP
    selector:
        app: admin-app
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
