FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

COPY dist/apps/admin-api/net8.0/linux-arm64 ./
COPY apps/admin-api/wait-for-postgres.sh ./wait-for-postgres.sh
RUN chmod +x ./wait-for-postgres.sh

ENV DOTNET_ENVIRONMENT=Staging

EXPOSE 9102
ENTRYPOINT ["./wait-for-postgres.sh", "postgres-service-staging", "dotnet", "EDb.AdminApi.dll"]
