---
apiVersion: v1
kind: Service
metadata:
    name: edb-webshop-api-prod-service
    labels:
        app: webshop-api-prod
spec:
    type: ClusterIP
    selector:
        app: webshop-api-prod
    ports:
        - protocol: TCP
          port: 8000
          targetPort: 8000
