apiVersion: v1
kind: Service
metadata:
  name: admin-api
  labels:
    app: admin-api
spec:
  type: ClusterIP
  selector:
    app: admin-api
  ports:
    - protocol: TCP
      port: 9102
      targetPort: 9102
