apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-staging
  namespace: auth
  labels:
    app: keycloak-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-staging
  template:
    metadata:
      labels:
        app: keycloak-staging
    spec:
      # Uncomment if your Docker Hub repo is private
      # imagePullSecrets:
      #   - name: dockerhub-creds
      containers:
        - name: keycloak
          image: eliasdb/keycloak-edb:26.2.4-v20
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            # Bootstrap admin
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: 'admin'
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: 'admin'

            # External hostname
            - name: KC_HOSTNAME
              value: 'https://keycloak.staging.eliasdebock.com'

            # Custom theme
            - name: KC_SPI_THEME_LOGIN_DEFAULT
              value: 'edb-theme'

            # PostgreSQL connection
            - name: KC_DB
              value: 'postgres'
            - name: KC_DB_URL
              value: 'jdbc:postgresql://postgres-service-staging.default:5432/mydatabase'
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-staging
                  key: POSTGRES_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-staging
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-staging
                  key: POSTGRES_DB
