apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend
    namespace: default
    labels:
        app: backend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: backend
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
                - name: vue-node-app-backend-dev
                  image: vue-node-app-backend
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 9100
                        protocol: TCP
                  env:
                      - name: JWT_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: node-app-secrets
                                key: JWT_SECRET
                      - name: DATABASE_URL
                        valueFrom:
                            secretKeyRef:
                                name: node-app-secrets
                                key: DATABASE_URL
                  readinessProbe:
                      httpGet:
                          path: /api/health
                          port: 9100
                      initialDelaySeconds: 5
                      periodSeconds: 10
                      timeoutSeconds: 5
                      failureThreshold: 3
                  livenessProbe:
                      httpGet:
                          path: /api/health
                          port: 9100
                      initialDelaySeconds: 15
                      periodSeconds: 20
                      timeoutSeconds: 5
                      failureThreshold: 3
            restartPolicy: Always
