apiVersion: v1
kind: Service
metadata:
    name: backend-service
    labels:
        app: backend
spec:
    type: LoadBalancer
    selector:
        app: backend
    ports:
        - protocol: TCP
          port: 9100
          targetPort: 9100
