apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-staging
  namespace: messaging
spec:
  template:
    spec:
      containers:
        - name: rabbitmq
          readinessProbe:
            exec:
              command:
                ['rabbitmq-diagnostics', '-q', 'check_port_listener', '5672']
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            exec:
              command: ['rabbitmq-diagnostics', '-q', 'ping']
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
