apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-staging
  namespace: argocd
spec:
  project: messaging
  source:
    repoURL: https://github.com/Eliasdb/eDB.git
    targetRevision: dev
    path: k8s/platform/messaging/rabbitmq/overlays/staging
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: messaging
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
