apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-prod
  namespace: auth # ✅ new namespace
  labels:
    app: keycloak-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-prod
  template:
    metadata:
      labels:
        app: keycloak-prod
    spec:
      containers:
        - name: keycloak
          image: eliasdb/keycloak-edb:26.2.4-v19
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            # bootstrap admin
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: 'admin'
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: 'admin'

            # public URL where users reach Keycloak
            - name: KC_HOSTNAME
              value: 'https://auth.eliasdebock.com' # ✅ updated host, no /keycloak path

            # make your theme the default login UI
            - name: KC_SPI_THEME_LOGIN_DEFAULT
              value: 'edb-theme'

            # ---------- Postgres (production) ----------
            - name: KC_DB
              value: 'postgres'
            - name: KC_DB_URL
              value: 'jdbc:postgresql://postgres-service-prod.default:5432/mydatabase'
              # ✅ explicit namespace if Postgres stays in "default"
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-prod
                  key: POSTGRES_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-prod
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-prod
                  key: POSTGRES_DB
