apiVersion: v1
kind: Service
metadata:
  name: platform-api
  labels:
    app: platform-api
spec:
  type: ClusterIP
  selector:
    app: platform-api
  ports:
    - protocol: TCP
      port: 9101
      targetPort: 9101
