apiVersion: v1
items:
- apiVersion: cert-manager.io/v1
  kind: ClusterIssuer
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cert-manager.io/v1","kind":"ClusterIssuer","metadata":{"annotations":{},"name":"letsencrypt-prod"},"spec":{"acme":{"email":"elias.db3@gmail.com","privateKeySecretRef":{"name":"letsencrypt-prod"},"server":"https://acme-v02.api.letsencrypt.org/directory","solvers":[{"http01":{"ingress":{"class":"nginx"}}}]}}}
    creationTimestamp: "2024-12-10T13:45:31Z"
    generation: 1
    name: letsencrypt-prod
    resourceVersion: "25107"
    uid: 5b2729aa-845b-4edb-95d1-b48b77e37b14
  spec:
    acme:
      email: elias.db3@gmail.com
      privateKeySecretRef:
        name: letsencrypt-prod
      server: https://acme-v02.api.letsencrypt.org/directory
      solvers:
      - http01:
          ingress:
            class: nginx
  status:
    acme:
      lastPrivateKeyHash: jlbq4BiS6wLGMPYov0vxYgOSpJWG5OQ3wiY1lEkGzNE=
      lastRegisteredEmail: elias.db3@gmail.com
      uri: https://acme-v02.api.letsencrypt.org/acme/acct/2105104427
    conditions:
    - lastTransitionTime: "2024-12-10T13:45:32Z"
      message: The ACME account was registered with the ACME server
      observedGeneration: 1
      reason: ACMEAccountRegistered
      status: "True"
      type: Ready
- apiVersion: cert-manager.io/v1
  kind: ClusterIssuer
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cert-manager.io/v1","kind":"ClusterIssuer","metadata":{"annotations":{},"name":"letsencrypt-production"},"spec":{"acme":{"email":"elias.db3@gmail.com","privateKeySecretRef":{"name":"letsencrypt-production"},"server":"https://acme-v02.api.letsencrypt.org/directory","solvers":[{"http01":{"ingress":{"class":"nginx"}}}]}}}
    creationTimestamp: "2025-02-24T10:00:39Z"
    generation: 1
    name: letsencrypt-production
    resourceVersion: "3768005"
    uid: de3f9fc8-ddca-41c7-808e-13096728d786
  spec:
    acme:
      email: elias.db3@gmail.com
      privateKeySecretRef:
        name: letsencrypt-production
      server: https://acme-v02.api.letsencrypt.org/directory
      solvers:
      - http01:
          ingress:
            class: nginx
  status:
    acme:
      lastPrivateKeyHash: IKEzTs91Qzwbe3I5U1SUacOBO5S/YKwL0Hj0jU40Mgw=
      lastRegisteredEmail: elias.db3@gmail.com
      uri: https://acme-v02.api.letsencrypt.org/acme/acct/2246875775
    conditions:
    - lastTransitionTime: "2025-02-24T10:00:41Z"
      message: The ACME account was registered with the ACME server
      observedGeneration: 1
      reason: ACMEAccountRegistered
      status: "True"
      type: Ready
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cert-manager.io/v1","kind":"Certificate","metadata":{"annotations":{},"name":"api-prod-tls","namespace":"default"},"spec":{"commonName":"api.eliasdebock.com","dnsNames":["api.eliasdebock.com"],"issuerRef":{"kind":"ClusterIssuer","name":"letsencrypt-production"},"secretName":"api-prod-tls"}}
    creationTimestamp: "2025-02-24T10:12:31Z"
    generation: 1
    name: api-prod-tls
    namespace: default
    resourceVersion: "12648147"
    uid: bed1bfe9-3cca-43d1-b73c-5c45a3b1bf14
  spec:
    commonName: api.eliasdebock.com
    dnsNames:
    - api.eliasdebock.com
    issuerRef:
      kind: ClusterIssuer
      name: letsencrypt-production
    secretName: api-prod-tls
  status:
    conditions:
    - lastTransitionTime: "2025-02-24T10:12:34Z"
      message: Certificate is up to date and has not expired
      observedGeneration: 1
      reason: Ready
      status: "True"
      type: Ready
    notAfter: "2025-11-21T06:19:38Z"
    notBefore: "2025-08-23T06:19:39Z"
    renewalTime: "2025-10-22T06:19:38Z"
    revision: 4
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cert-manager.io/v1","kind":"Certificate","metadata":{"annotations":{},"name":"app-prod-tls","namespace":"default"},"spec":{"commonName":"app.eliasdebock.com","dnsNames":["app.eliasdebock.com"],"issuerRef":{"kind":"ClusterIssuer","name":"letsencrypt-production"},"secretName":"app-prod-tls"}}
    creationTimestamp: "2025-02-24T10:12:31Z"
    generation: 1
    name: app-prod-tls
    namespace: default
    resourceVersion: "12648162"
    uid: d29bae92-cb6f-442d-98b1-54d18f5cea57
  spec:
    commonName: app.eliasdebock.com
    dnsNames:
    - app.eliasdebock.com
    issuerRef:
      kind: ClusterIssuer
      name: letsencrypt-production
    secretName: app-prod-tls
  status:
    conditions:
    - lastTransitionTime: "2025-02-24T10:12:33Z"
      message: Certificate is up to date and has not expired
      observedGeneration: 1
      reason: Ready
      status: "True"
      type: Ready
    notAfter: "2025-11-21T06:19:39Z"
    notBefore: "2025-08-23T06:19:40Z"
    renewalTime: "2025-10-22T06:19:39Z"
    revision: 4
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    creationTimestamp: "2025-08-20T10:38:25Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: rabbitmq
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/version: 4.1.3
      helm.sh/chart: rabbitmq-16.0.13
    name: rabbitmq.eliasdebock.com-tls
    namespace: messaging
    ownerReferences:
    - apiVersion: networking.k8s.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Ingress
      name: rabbitmq
      uid: c88d7fff-785a-4a4a-ae1b-5155ecdcd1fb
    resourceVersion: "12520435"
    uid: 70d6e9d3-a36e-48e9-95b1-0051c5ddb16d
  spec:
    dnsNames:
    - rabbitmq.eliasdebock.com
    issuerRef:
      group: cert-manager.io
      kind: ClusterIssuer
      name: letsencrypt-production
    secretName: rabbitmq.eliasdebock.com-tls
    usages:
    - digital signature
    - key encipherment
  status:
    conditions:
    - lastTransitionTime: "2025-08-20T17:08:14Z"
      message: Certificate is up to date and has not expired
      observedGeneration: 1
      reason: Ready
      status: "True"
      type: Ready
    notAfter: "2025-11-18T16:09:41Z"
    notBefore: "2025-08-20T16:09:42Z"
    renewalTime: "2025-10-19T16:09:41Z"
    revision: 1
kind: List
metadata:
  resourceVersion: ""
