apiVersion: skaffold/v2beta26
kind: Config
metadata:
    name: my-app
build:
    tagPolicy:
        gitCommit: {} # Automatically tags images with the current Git commit SHA
    artifacts:
        - image: edb-app
          context: eDB/
          docker:
              dockerfile: Dockerfile.dev
          sync:
              manual:
                  - src: '**/*.ts'
                    dest: .
                  - src: '**/*.html'
                    dest: .
                  - src: '**/*.scss'
                    dest: .

        - image: api
          context: api/
          docker:
              dockerfile: Dockerfile.dev
          sync:
              manual:
                  - src: '**/*.cs'
                    dest: .
                  - src: '**/*.json'
                    dest: .
deploy:
    kubectl:
        manifests:
            - k8s/dev/adminer/*.yaml
            - k8s/dev/db/*.yaml
            - k8s/dev/api/*.yaml
            - k8s/dev/eDB/*.yaml
            - k8s/prod/ingress/*.yaml
