apiVersion: skaffold/v2beta26
kind: Config
metadata:
    name: my-app
build:
    tagPolicy:
        gitCommit: {} # Automatically tags images with the current Git commit SHA
    artifacts:
        - image: vue-node-app-frontend
          context: frontend/
          docker:
              dockerfile: Dockerfile.dev
          sync:
              manual:
                  - src: '**/*.ts'
                    dest: .
                  - src: '**/*.js'
                    dest: .
                  - src: '**/*.json'
                    dest: .
                  - src: '**/*.vue'
                    dest: .
        - image: api # Add your C# .NET API image here
          context: api/ # Specify the context for your API code
          docker:
              dockerfile: Dockerfile.dev # Specify your API Dockerfile if different
          sync:
              manual:
                  - src: '**/*.cs' # Sync C# files
                    dest: .
                  - src: '**/*.json' # Sync JSON configuration files
                    dest: .
deploy:
    kubectl:
        manifests:
            - k8s/frontend/*.yaml
            - k8s/db/*.yaml
            - k8s/adminer/*.yaml
            - k8s/api/*.yaml # Include the manifests for your API deployment
