apiVersion: skaffold/v2beta26
kind: Config
metadata:
    name: my-app
build:
    tagPolicy:
        sha256: {} # Avoid Git state affecting rebuilds
    artifacts:
        - image: edb-app
          context: eDB/
          docker:
              dockerfile: Dockerfile.dev
          sync:
              manual:
                  - src: 'src/**/*'
                    dest: /app/src
                  - src: 'styles/**/*.scss'
                    dest: /app/styles
        - image: api
          context: api/
          docker:
              dockerfile: Dockerfile.dev
          sync:
              manual:
                  - src: '**/*.cs'
                    dest: .
                  - src: '**/*.json'
                    dest: .
deploy:
    kubectl:
        manifests:
            - k8s/dev/adminer/*.yaml
            - k8s/dev/db/*.yaml
            - k8s/dev/api/*.yaml
            - k8s/dev/eDB/*.yaml
