apiVersion: skaffold/v2beta26
kind: Config
metadata:
    name: my-app
build:
    tagPolicy:
        gitCommit: {} # Automatically tags images with the current Git commit SHA
    artifacts:
        - image: vue-node-app-backend
          context: backend/
          docker:
              dockerfile: Dockerfile.dev
          sync:
              manual:
                  - src: '**/*.ts' # Sync TypeScript files
                    dest: .
                  - src: '**/*.js' # Sync JavaScript files
                    dest: .
                  - src: '**/*.json' # Sync JSON configuration files
                    dest: .
                  - src: '**/*.vue' # Sync Vue component files
                    dest: .
        - image: vue-node-app-frontend
          context: frontend/
          docker:
              dockerfile: Dockerfile.dev
          sync:
              manual:
                  - src: '**/*.ts'
                    dest: .
                  - src: '**/*.js'
                    dest: .
                  - src: '**/*.json'
                    dest: .
                  - src: '**/*.vue'
                    dest: .
        - image: api  # Add your C# .NET API image here
          context: api/  # Specify the context for your API code
          docker:
              dockerfile: Dockerfile.dev  # Specify your API Dockerfile if different
          sync:
              manual:
                  - src: '**/*.cs'  # Sync C# files
                    dest: .
                  - src: '**/*.json' # Sync JSON configuration files
                    dest: .
deploy:
    kubectl:
        manifests:
            - k8s/backend/*.yaml
            - k8s/frontend/*.yaml
            - k8s/database/*.yaml
            - k8s/adminer/*.yaml
            - k8s/api/*.yaml  # Include the manifests for your API deployment
