apiVersion: skaffold/v2beta26
kind: Config
metadata:
    name: my-app
build:
    tagPolicy:
        gitCommit: {} # Automatically tags images with the current Git commit SHA
    artifacts:
        - image: frontend
          context: client/
          docker:
              dockerfile: Dockerfile.dev
          sync:
              manual:
                  - src: '**/*.ts'
                    dest: .
                  - src: '**/*.js'
                    dest: .
                  - src: '**/*.json'
                    dest: .
                  - src: '**/*.html'
                    dest: .
        - image: api
          context: api/
          docker:
              dockerfile: Dockerfile.dev
          sync:
              manual:
                  - src: '**/*.cs'
                    dest: .
                  - src: '**/*.json'
                    dest: .
deploy:
    kubectl:
        manifests:
            - k8s/client/*.yaml
            - k8s/api/*.yaml
            - k8s/db/*.yaml
            - k8s/adminer/*.yaml
