apiVersion: skaffold/v2beta26
kind: Config
metadata:
    name: my-app
build:
    local:
        push: false
        useBuildkit: true
    tagPolicy:
        sha256: {}
    artifacts:
        - image: platform-app-dev
          context: eDB
          docker:
              dockerfile: docker/Dockerfile.web.dev
          sync:
              infer: []
        - image: admin-app-dev
          context: eDB
          docker:
              dockerfile: docker/Dockerfile.admin.dev
          sync:
              infer: []
        - image: platform-api-dev
          context: PlatformAPI/
          docker:
              dockerfile: Dockerfile.dev
          sync:
              infer: []

deploy:
    kubectl:
        manifests:
            - k8s/dev/adminer/*.yaml
            - k8s/dev/db/*.yaml
            - k8s/dev/PlatformAPI/*.yaml
            - k8s/dev/eDB/*.yaml
            - k8s/dev/eDB-admin/*.yaml
