apiVersion: skaffold/v2beta26
kind: Config
metadata:
    name: my-app
build:
    local:
        push: false
        useBuildkit: true
    tagPolicy:
        sha256: {} # Avoid Git state affecting rebuilds
    artifacts:
        - image: edb-app
          context: eDB/
          docker:
              dockerfile: Dockerfile.dev
          sync:
              infer: []
        - image: api
          context: api/
          docker:
              dockerfile: Dockerfile.dev
          sync:
              infer: []
deploy:
    kubectl:
        manifests:
            - k8s/dev/adminer/*.yaml
            - k8s/dev/db/*.yaml
            - k8s/dev/api/*.yaml
            - k8s/dev/eDB/*.yaml
