apiVersion: skaffold/v2beta26
kind: Config
metadata:
    name: my-app
build:
    local:
        push: false
        useBuildkit: true
    tagPolicy:
        sha256: {} # Avoid Git state affecting rebuilds
    artifacts:
        - image: platform-app-dev
          context: eDB/
          docker:
              dockerfile: Dockerfile.dev
          sync:
              infer: []
        - image: platform-api-dev
          context: PlatformAPI/
          docker:
              dockerfile: Dockerfile.dev
          sync:
              infer: []
        - image: admin-app-dev
          context: eDB/ # Path to your admin app directory
          docker:
              dockerfile: Dockerfile.dev # Specify the Dockerfile for the admin app
          sync:
              infer: []
deploy:
    kubectl:
        manifests:
            - k8s/dev/adminer/*.yaml
            - k8s/dev/db/*.yaml
            - k8s/dev/PlatformAPI/*.yaml
            - k8s/dev/eDB/*.yaml
            - k8s/dev/eDB-admin/*.yaml # Path to your admin app Kubernetes manifests
