apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -staging
namespace: default
resources:
  - ../../base
patches:
  - path: patch-env.yaml
images:
  # Set a concrete tag for robustness (adjust tag as needed)
  - name: eliasdb/edb
    # newTag: pr-89-staging
