apiVersion: apps/v1
kind: Deployment
metadata:
    name: db
    namespace: default
    labels:
        app: db
spec:
    replicas: 1
    selector:
        matchLabels:
            app: db
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: db
        spec:
            containers:
                - name: my-mysql-db
                  image: mysql:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 3306
                        protocol: TCP
                  env:
                      - name: MYSQL_DATABASE
                        valueFrom:
                            secretKeyRef:
                                name: mysql-db-secrets
                                key: MYSQL_DATABASE
                      - name: MYSQL_USER
                        valueFrom:
                            secretKeyRef:
                                name: mysql-db-secrets
                                key: MYSQL_USER
                      - name: MYSQL_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mysql-db-secrets
                                key: MYSQL_PASSWORD
                      - name: MYSQL_ROOT_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mysql-db-secrets
                                key: MYSQL_ROOT_PASSWORD
                  livenessProbe:
                      exec:
                          command:
                              - mysqladmin
                              - ping
                              - -h
                              - localhost
                      failureThreshold: 5
                      periodSeconds: 10
                      timeoutSeconds: 5
                  volumeMounts:
                      - mountPath: /var/lib/mysql
                        name: mysql-data
            restartPolicy: Always
            volumes:
                - name: mysql-data
                  persistentVolumeClaim:
                      claimName: mysql-data # Ensure this matches your PVC name
