apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-data
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: '' # Match the PV with no StorageClass
