apiVersion: v1
kind: PersistentVolume
metadata:
    name: mysql-pv
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: /Users/elias/Desktop/Projects/Portfolio2024/Fullstack/k8s-data/db # Your specified path
