# Use the official Node.js image
FROM node:18 AS dev

# Set the working directory
WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm

# Set SHELL, PNPM_HOME, and PATH for global installations
ENV SHELL=/bin/sh
ENV PNPM_HOME="/root/.pnpm"
ENV PATH="${PNPM_HOME}:${PATH}"

# Install netcat-openbsd for database checks
RUN apt-get update && apt-get install -y netcat-openbsd

# Copy package.json and lock file
COPY package*.json ./

# Install dependencies
RUN pnpm install

# Install nodemon and ts-node globally for hot reloading
RUN pnpm add -g nodemon ts-node

# Copy the rest of the application code
COPY . .

# Copy the wait-for-it.sh script
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

# Run migrations first, then start the application with nodemon
CMD ["/bin/sh", "-c", "/wait-for-it.sh db -- npx prisma migrate deploy --schema=src/prisma/schema.prisma && npx prisma generate --schema=src/prisma/schema.prisma && nodemon --watch src --exec 'npx ts-node src/app.ts'"]
