# Use the official Node.js image
FROM node:18 AS dev

# Set the working directory
WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm

# Set environment variables
ENV SHELL=/bin/sh
ENV PNPM_HOME="/root/.pnpm"
ENV PATH="/app/node_modules/.bin:${PNPM_HOME}:${PATH}"
ENV NODE_ENV=development

# Install netcat-openbsd for database checks
RUN apt-get update && apt-get install -y netcat-openbsd

# Copy package.json and lock file
COPY package*.json pnpm-lock.yaml ./

# Install dependencies (including devDependencies)
RUN pnpm install

# Copy the rest of the application code
COPY . .

# Copy the wait-for-it.sh script
COPY /wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

# Start the application
CMD ["pnpm", "run", "dev:start"]
