FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime

# Install nc (netcat)
RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY dist/apps/server/admin-api ./ 

COPY apps/server/admin-api/wait-for-postgres.sh ./wait-for-postgres.sh
RUN chmod +x ./wait-for-postgres.sh

ENV DOTNET_ENVIRONMENT=Staging

EXPOSE 9102
ENTRYPOINT ["./wait-for-postgres.sh", "postgres-service-staging", "dotnet", "EDb.AdminApi.dll"]
