apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-prod
  namespace: argocd
spec:
  project: networking
  source:
    repoURL: https://github.com/Eliasdb/eDB.git
    targetRevision: main
    path: k8s/platform/networking/ingress/prod
    kustomize: {}
  destination:
    name: prod
    namespace: default # required field; resources define their own namespaces
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
