---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: my-ingress
    namespace: default
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
    ingressClassName: nginx
    rules:
        - host: app.eliasdebock.com
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: edb-nx-prod-service
                            port:
                                number: 80
        - host: api.eliasdebock.com
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: edb-api-prod-service
                            port:
                                number: 9101
    tls:
        - hosts:
              - app.eliasdebock.com
          secretName: app-tls
        - hosts:
              - api.eliasdebock.com
          secretName: api-tls
