apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: app-prod-tls
    namespace: default
spec:
    secretName: app-prod-tls
    issuerRef:
        name: letsencrypt-production
        kind: ClusterIssuer
    commonName: app.eliasdebock.com
    dnsNames:
        - app.eliasdebock.com
