apiVersion: apps/v1
kind: Deployment
metadata:
    name: admin-api-prod
    namespace: default
    labels:
        app: admin-api-prod
spec:
    replicas: 2
    selector:
        matchLabels:
            app: admin-api-prod
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: admin-api-prod
        spec:
            containers:
                - name: admin-api
                  image: eliasdb/admin-api:latest-prod
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 9102
                        protocol: TCP
                  env:
                      - name: ASPNETCORE_ENVIRONMENT
                        value: 'Production'

                      - name: ConnectionStrings__DefaultConnection
                        valueFrom:
                            secretKeyRef:
                                name: postgres-secret-prod
                                key: CONNECTION_STRING

                      - name: Jwt__Key
                        valueFrom:
                            secretKeyRef:
                                name: jwt-secret-prod
                                key: JWT_KEY

                      - name: ASPNETCORE_URLS
                        value: 'http://+:9102'

                  resources:
                      requests:
                          memory: '256Mi'
                          cpu: '500m'
                      limits:
                          memory: '1Gi'
                          cpu: '1'
