---
apiVersion: v1
kind: Service
metadata:
    name: edb-admin-api-prod-service
    labels:
        app: admin-api-prod
spec:
    type: ClusterIP
    selector:
        app: admin-api-prod
    ports:
        - protocol: TCP
          port: 9102
          targetPort: 9102
