apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Eliasdb/eDB.git
    targetRevision: dev
    path: k8s/argocd/staging
    kustomize: {} # 👈 tell Argo to use Kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd # child Applications are created in argocd ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  # This lets Argo warn if a child Application disappears from Git
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      namespace: argocd
      jsonPointers:
        - /status
