# k8s/argocd/prod/apps/identity/keycloak-prod.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: identity
  source:
    repoURL: https://github.com/Eliasdb/eDB.git
    targetRevision: main
    path: k8s/platform/identity/keycloak/overlays/prod
  destination:
    name: prod # 👈 prod cluster by name
    namespace: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
