---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-api-prod
  namespace: default
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: eliasdb/platform-api:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 9101
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: 'Production'
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-prod
                  key: CONNECTION_STRING
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: jwt-secret-prod
                  key: JWT_KEY

            # 🔐 Keycloak environment variables
            - name: Keycloak__ClientId
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret-prod
                  key: CLIENT_ID

            - name: Keycloak__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret-prod
                  key: CLIENT_SECRET

            - name: Keycloak__BaseUrl
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret-prod
                  key: BASE_URL

            - name: Keycloak__Realm
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret-prod
                  key: REALM
            - name: ADMIN_API_URL
              value: 'https://api.eliasdebock.com/admin/swagger/v1/swagger.json'
            - name: WEBSHOP_API_URL
              value: 'https://api.eliasdebock.com/webshop/api.json'

          #   readinessProbe:
          #       httpGet:
          #           path: /health
          #           port: 9101
          #       initialDelaySeconds: 5
          #       periodSeconds: 10
          #       timeoutSeconds: 5
          #       failureThreshold: 3
          #   livenessProbe:
          #       httpGet:
          #           path: /health
          #           port: 9101
          #       initialDelaySeconds: 15
          #       periodSeconds: 20
          #       timeoutSeconds: 5
          #       failureThreshold: 3
          resources:
            requests:
              memory: '256Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
