apiVersion: v1
kind: Service
metadata:
    name: frontend-service
    namespace: default
    labels:
        app: frontend
spec:
    type: LoadBalancer
    selector:
        app: frontend
    ports:
        - protocol: TCP
          port: 8080 # The port accessible externally
          targetPort: 8080 # The port on the container that Vite is running on
