# k8s/infra/monitoring/loki/values-staging.yaml

deploymentMode: SingleBinary
fullnameOverride: loki

# Run a single pod with a PVC
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 20Gi
    # storageClass: <your-storage-class>
  # make the PVC writeable for loki user
  extraInitContainers:
    - name: init-fix-perms
      image: busybox:1.36
      command: ['sh', '-c', 'chown -R 10001:10001 /var/loki || true']
      volumeMounts:
        - name: storage
          mountPath: /var/loki

# ensure scalable targets are off
read: { replicas: 0 }
write: { replicas: 0 }
backend: { replicas: 0 }

# pod FS permissions
podSecurityContext:
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  fsGroupChangePolicy: OnRootMismatch

# Simplify: disable optional caches for now
chunksCache:
  enabled: false
resultsCache:
  enabled: false

service:
  type: ClusterIP
  ports:
    http: 3100

# ---- Provide an explicit Loki config (Helm will tpl this) ----
loki:
  config: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    memberlist:
      join_members:
        - {{ include "loki.memberlist" . }}

    common:
      path_prefix: /var/loki
      replication_factor: 1
      storage:
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules

    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/boltdb-cache
        shared_store: filesystem
      filesystem:
        directory: /var/loki/chunks

    schema_config:
      configs:
        - from: 2024-01-01
          store: boltdb-shipper
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    compactor:
      working_directory: /var/loki/compactor
      compaction_interval: 5m
      retention_enabled: true
      delete_request_store: filesystem

    limits_config:
      retention_period: 7d
      allow_structured_metadata: false
