# k8s/infra/monitoring/loki/values-staging.yaml

# Run Loki in single process
deploymentMode: SingleBinary

fullnameOverride: loki

# Only single-binary; turn off scalable targets
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 20Gi
    # storageClass: <your-storage-class>

read: { replicas: 0 }
write: { replicas: 0 }
backend: { replicas: 0 }

# Make sure the pod can write to the PVC
podSecurityContext:
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  fsGroupChangePolicy: OnRootMismatch

service:
  type: ClusterIP
  ports:
    http: 3100

# -------- Loki config (keys match chart expectations) --------
loki:
  auth_enabled: false

  server:
    http_listen_port: 3100

  # The chart's helpers reference this path; keep it simple but present
  storage:
    type: filesystem
    bucketNames:
      chunks: chunks
      ruler: ruler

  # camelCase here (chart renders to `common:` in loki.yaml)
  commonConfig:
    replication_factor: 1

  # camelCase here (chart renders to `schema_config:`)
  schemaConfig:
    configs:
      - from: 2024-01-01
        store: boltdb-shipper
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

  # underscore here (chart renders to `storage_config:` as-is)
  storage_config:
    boltdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/boltdb-cache
      shared_store: filesystem
    filesystem:
      directory: /var/loki/chunks

  compactor:
    working_directory: /var/loki/compactor
    compaction_interval: 5m
    retention_enabled: true
    delete_request_store: filesystem # required when retention is enabled

  limits_config:
    retention_period: 7d
    allow_structured_metadata: false # until/if you migrate to TSDB
