# Force single-process Loki
deploymentMode: SingleBinary

fullnameOverride: loki

# ✅ keep ONLY singleBinary replicas
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 20Gi
    # storageClass: <your-storage-class>

# 🚫 ensure scalable targets are OFF
read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0

loki:
  auth_enabled: false
  server:
    http_listen_port: 3100

  # filesystem storage is fine for SingleBinary
  storage:
    type: filesystem

  commonConfig:
    replication_factor: 1

  schemaConfig:
    configs:
      - from: 2024-01-01
        store: boltdb-shipper
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

  compactor:
    working_directory: /data/compactor
    compaction_interval: 5m
    retention_enabled: true

  limits_config:
    retention_period: 7d

service:
  type: ClusterIP
  ports:
    http: 3100
