# Force single-process Loki
deploymentMode: SingleBinary

fullnameOverride: loki

# ✅ keep ONLY single-binary; zero scalable targets
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 20Gi
    # storageClass: <your-storage-class>  # uncomment if you need a specific SC

read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0

# Help with PVC permissions
podSecurityContext:
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  fsGroupChangePolicy: 'OnRootMismatch'

service:
  type: ClusterIP
  ports:
    http: 3100

# ---- Loki configuration (this renders into loki.yaml) ----
loki:
  auth_enabled: false

  server:
    http_listen_port: 3100

  # Common paths + local filesystem storage layout
  common:
    path_prefix: /var/loki
    replication_factor: 1
    storage:
      filesystem:
        chunks_directory: /var/loki/chunks
        rules_directory: /var/loki/rules

  # Index & schema (boltdb-shipper on filesystem)
  schema_config:
    configs:
      - from: 2024-01-01
        store: boltdb-shipper
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

  storage_config:
    boltdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/boltdb-cache
      shared_store: filesystem
    filesystem:
      directory: /var/loki/chunks

  # Retention requires delete_request_store
  compactor:
    working_directory: /var/loki/compactor
    compaction_interval: 5m
    retention_enabled: true
    delete_request_store: filesystem

  # Keep it simple until you migrate to TSDB
  limits_config:
    retention_period: 7d
    allow_structured_metadata: false
