# Run Loki in single-process mode (no read/write/backend split)
deploymentMode: SingleBinary

fullnameOverride: loki

loki:
  auth_enabled: false
  server:
    http_listen_port: 3100

  # Use filesystem (OK for single-binary; NOT OK for scalable/distributed)
  storage:
    type: filesystem

  commonConfig:
    replication_factor: 1

  schemaConfig:
    configs:
      - from: 2024-01-01
        store: boltdb-shipper
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

  compactor:
    working_directory: /data/compactor
    compaction_interval: 5m
    retention_enabled: true

  limits_config:
    retention_period: 7d

# Persistence for the single-binary pod
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 20Gi
    # storageClass: <your-storage-class>   # uncomment if needed

service:
  type: ClusterIP
  ports:
    http: 3100
