apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-staging
  namespace: messaging
  labels:
    app: rabbitmq-staging
spec:
  type: ClusterIP
  selector:
    app: rabbitmq-staging
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: management
      port: 15672
      targetPort: management
