apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-pvc-prod
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 40Gi # Match PV capacity
    storageClassName: '' # Match PV with no StorageClass
