---
apiVersion: v1
kind: Service
metadata:
    name: postgres-service-staging
    labels:
        app: postgres-staging
spec:
    type: ClusterIP # Internal communication only
    ports:
        - port: 5432
          targetPort: 5432
    selector:
        app: postgres-staging
