/* do not change this file, it is auto generated by storybook. */
import { start, updateView, View } from '@storybook/react-native';

import "@storybook/addon-ondevice-controls/register";
import "@storybook/addon-ondevice-actions/register";
import "@storybook/addon-ondevice-backgrounds/register";

const normalizedStories = [
  {
    titlePrefix: "",
    directory: "./src",
    files: "**/*.stories.@(ts|tsx|js|jsx)",
    importPathMatcher: /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(ts|tsx|js|jsx))$/,
    // @ts-expect-error storybook auto-generates this require context
    req: require.context(
      '../src',
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(ts|tsx|js|jsx))$/
    ),
  }
];


declare global {
  var view: View;
  var STORIES: typeof normalizedStories;
}


const annotations = [
  require('./preview'),
  require("@storybook/react-native/preview"),
  require('@storybook/addon-docs/preview')
];

global.STORIES = normalizedStories;

// @ts-expect-error optional HMR APIs may not exist in RN
module?.hot?.accept?.();



if (!global.view) {
  global.view = start({
    annotations,
    storyEntries: normalizedStories,

  });
} else {
  updateView(global.view, annotations, normalizedStories);
}

export const view: View = global.view;
