apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-prod
    namespace: default
    labels:
        app: api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: api
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: api
        spec:
            containers:
                - name: api
                  image: eliasdb/edb-api:v1.0.237-prod
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 9101
                        protocol: TCP
                  env:
                      - name: ASPNETCORE_ENVIRONMENT
                        value: 'Production'
                      - name: ConnectionStrings__DefaultConnection
                        valueFrom:
                            secretKeyRef:
                                name: postgres-secret-prod
                                key: CONNECTION_STRING
                      - name: Jwt__Key
                        valueFrom:
                            secretKeyRef:
                                name: jwt-secret-prod
                                key: JWT_KEY
                  readinessProbe:
                      httpGet:
                          path: /health
                          port: 9101
                      initialDelaySeconds: 5
                      periodSeconds: 10
                      timeoutSeconds: 5
                      failureThreshold: 3
                  livenessProbe:
                      httpGet:
                          path: /health
                          port: 9101
                      initialDelaySeconds: 15
                      periodSeconds: 20
                      timeoutSeconds: 5
                      failureThreshold: 3
                  resources:
                      requests:
                          memory: '256Mi'
                          cpu: '500m'
                      limits:
                          memory: '1Gi'
                          cpu: '1'
