apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-prod
    namespace: default
    labels:
        app: api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: api
    template:
        metadata:
            labels:
                app: api
        spec:
            containers:
                - name: api
                  image: eliasdb/edb-api:${IMAGE_TAG}
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 9101
                        protocol: TCP
                  env:
                      - name: ASPNETCORE_ENVIRONMENT
                        value: 'Production'
                      - name: ConnectionStrings__DefaultConnection
                        valueFrom:
                            secretKeyRef:
                                name: postgres-secret-prod
                                key: CONNECTION_STRING
                      - name: Jwt__Key
                        valueFrom:
                            secretKeyRef:
                                name: jwt-secret-prod
                                key: JWT_KEY
