apiVersion: v1
kind: Service
metadata:
    name: edb-api-prod-service
    labels:
        app: api
spec:
    type: ClusterIP
    selector:
        app: api
    ports:
        - protocol: TCP
          port: 9101
          targetPort: 9101
