apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis-staging
    namespace: default
    labels:
        app: redis-staging
spec:
    replicas: 1
    selector:
        matchLabels:
            app: redis-staging
    template:
        metadata:
            labels:
                app: redis-staging
        spec:
            containers:
                - name: redis
                  image: redis:7.4
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 6379
                  resources:
                      requests:
                          memory: '256Mi'
                          cpu: '250m'
                      limits:
                          memory: '512Mi'
                          cpu: '500m'
                  volumeMounts:
                      - name: redis-data
                        mountPath: /data
            volumes:
                - name: redis-data
                  emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
    name: redis-service-staging
    namespace: default
spec:
    selector:
        app: redis-staging
    ports:
        - protocol: TCP
          port: 6379
          targetPort: 6379
    type: ClusterIP
