apiVersion: apps/v1
kind: Deployment
metadata:
  name: tools-invoices-api
spec:
  template:
    spec:
      containers:
        - name: tools-invoices-api
          image: eliasdb/tools-invoices-api:v1.0.0 # explicit release tag
          env:
            - name: ENVIRONMENT
              value: 'production'
