apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-staging
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx-argo
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.11.2
    helm:
      # Point Helm at the values file you keep in this repo
      valueFiles:
        - ../../infra/ingress-nginx/values-staging.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
