apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Eliasdb/eDB.git
    targetRevision: dev
    path: k8s/apps/rabbitmq # <- directory in your repo
    helm:
      releaseName: rabbitmq-staging
      valueFiles:
        - values-staging.yaml # <- RELATIVE to path above
  destination:
    server: https://kubernetes.default.svc
    namespace: messaging # or default, but be consistent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # - CreateNamespace=true
