apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webshop-api-staging
  namespace: argocd
  annotations:
    # Track the image and let Image Updater set the tag for staging
    argocd-image-updater.argoproj.io/image-list: webshop-api=eliasdb/webshop-api
    argocd-image-updater.argoproj.io/webshop-api.allow-tags: regexp:^pr-\d+-staging$
    argocd-image-updater.argoproj.io/webshop-api.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Eliasdb/eDB.git
    targetRevision: dev
    path: k8s/apps/webshop-api/overlays/staging
    kustomize:
      images:
        - webshop-api=eliasdb/webshop-api
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - PruneLast=true
