---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-pvc-staging
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 40Gi # Match PV capacity for staging
    storageClassName: '' # Match PV with no StorageClass
