# Base image for serving static files
FROM nginx:alpine

# Copy built files from CI/CD pipeline output
# Assuming the CI/CD pipeline outputs the build to 'dist/apps/eDB-admin'
COPY dist/apps/eDB /etc/nginx/html/app

# Copy custom nginx configuration for the admin app
COPY apps/eDB/nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
