# meilisearch-service.yaml
apiVersion: v1
kind: Service
metadata:
    name: meilisearch-staging
    labels:
        app: meilisearch
spec:
    selector:
        app: meilisearch
    ports:
        - protocol: TCP
          port: 7700
          targetPort: 7700
    type: ClusterIP
