apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-prod
  namespace: argocd
spec:
  project: messaging
  source:
    repoURL: https://github.com/Eliasdb/eDB.git
    targetRevision: main
    path: k8s/platform/messaging/rabbitmq/overlays/prod
  destination:
    name: prod
    namespace: messaging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
