apiVersion: v1
kind: ConfigMap
metadata:
    labels:
        io.kompose.service: frontend
    name: frontend-cm0
data:
    VUE_APP_API_URL: 'https://api.example.com'
    VUE_APP_TITLE: 'My Vue Application'
