apiVersion: v1
kind: Service
metadata:
    name: frontend-service
    namespace: default
    labels:
        app: frontend
spec:
    type: LoadBalancer
    selector:
        app: frontend
    ports:
        - protocol: TCP
          port: 4200 # The port accessible externally
          targetPort: 4200 # The port on the container that Angular is running on
