apiVersion: v1
kind: Service
metadata:
    name: platform-api-service
    labels:
        app: platform-api-dev
spec:
    type: LoadBalancer
    selector:
        app: platform-api-dev
    ports:
        - protocol: TCP
          port: 9101
          targetPort: 9101
