apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-prod
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq
    targetRevision: 14.*
    helm:
      valueFiles:
        - k8s/apps/rabbitmq/values-prod.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
