apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -staging
namespace: default

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: admin-client
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: staging

images:
  # Let Argo CD Image Updater set the tag; fallback tag optional:
  - name: eliasdb/edb-admin
    # newTag: pr-266-staging
