# k8s/argocd/staging/apps/security/cert-manager.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: security
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.14.4 # 👈 set this explicitly (check your current version with kubectl get deployment -n cert-manager cert-manager -o yaml | grep chart)
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: false # keep false until first sync looks good
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
