# k8s/apps/meilisearch/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
nameSuffix: -prod
resources: [../../base]
patches:
  - path: patch-env.yaml
