apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch-prod # must match final name with nameSuffix
spec:
  template:
    spec:
      containers:
        - name: meilisearch
          env:
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: meilisearch-secret-prod
                  key: MEILI_MASTER_KEY
