{
 "title": "eDB logs",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Platform FE",
   "type": "logs",
   "description": "eDB logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"edb-nx\"}\n\t\n\n\n"
    }
   ]
  },
  {
   "title": "Admin FE",
   "type": "logs",
   "description": "eDB-admin logs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"admin-app\"}\n"
    }
   ]
  },
  {
   "title": "Platform API",
   "type": "logs",
   "description": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"api\"}"
    }
   ]
  },
  {
   "title": "Admin API",
   "type": "logs",
   "description": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"admin-api\"}"
    }
   ]
  },
  {
   "title": "Webshop API",
   "type": "logs",
   "description": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"webshop-api\"}"
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"postgres\"}\t"
    }
   ]
  },
  {
   "title": "Keycloak",
   "type": "logs",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"keycloak\"}\t"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"default\"}"
    }
   ]
  }
 ]
}