{
 "title": "eDB MAIN",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "description": "Real-time memory used by each pod in bytes.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  container_memory_usage_bytes{image!=\"\", container!=\"POD\", namespace=\"default\"}\n) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Uptime per Pod",
   "type": "timeseries",
   "description": "Duration each pod has been running since last restart.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(time() - kube_pod_start_time) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods Not Ready",
     "type": "timeseries",
     "description": "Number of pods in the cluster currently reporting Ready = false. Indicates potential startup delays, crashes, or readiness probe failures.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "kube_pod_status_ready{condition=\"true\"} == 0 and on(pod, namespace) kube_pod_status_phase{phase!=\"Succeeded\", phase!=\"Failed\"}\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Node Count",
     "type": "timeseries",
     "description": "Total number of Kubernetes nodes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      { "expr": "count(kube_node_info)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Pods per Namespace",
     "type": "timeseries",
     "description": "Total number of pods grouped by namespace. Useful to distinguish between system workloads and application workloads.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "count by (namespace) (kube_pod_info)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pod Restarts by Namespace",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_restarts_total) by (namespace)\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Capacity (Node)",
   "type": "stat",
   "description": "Total allocatable CPU per node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\"}) by (node)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space Available (%)",
   "type": "gauge",
   "description": "Shows remaining disk space on root volume.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * node_filesystem_free_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Total",
   "type": "stat",
   "description": "NVMe SSD capacity",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\", fstype!~\"tmpfs|overlay\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage (Root Volume)",
   "type": "timeseries",
   "description": "Disk space used on root mount / (excluding free space)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"} - node_filesystem_free_bytes{mountpoint=\"/\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg(node_memory_MemAvailable_bytes) by (instance) / avg(node_memory_MemTotal_bytes) by (instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (Node)",
   "type": "timeseries",
   "description": "Total CPU usage per node (excluding idle time)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) by (instance)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}