apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-api-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  source:
    repoURL: https://github.com/Eliasdb/eDB.git
    targetRevision: main
    path: k8s/product/admin-api/overlays/prod
  destination:
    name: prod # 👈 now targets the prod cluster you registered
    namespace: default # or your prod namespace
  syncPolicy:
    # For prod, keep manual unless you’re confident
    automated: { prune: false, selfHeal: false }
    syncOptions:
      - PrunePropagationPolicy=foreground
      - PruneLast=true
