apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tools-invoices-api-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # <-- add this
spec:
  project: default
  source:
    repoURL: https://github.com/Eliasdb/eDB.git
    targetRevision: main
    path: k8s/product/tools-invoices-api/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - PruneLast=true
