apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: app-tls
    namespace: default
spec:
    secretName: app-tls
    issuerRef:
        name: letsencrypt-production
        kind: ClusterIssuer
    commonName: app.staging.eliasdebock.com
    dnsNames:
        - app.staging.eliasdebock.com
