apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -staging
namespace: default
resources:
  - ../../base
patchesStrategicMerge:
  - patch.yaml
images:
  - name: eliasdb/admin-api
    newTag: ${IMAGE_TAG} # replaced by CI
