apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: messaging
  namespace: argocd
spec:
  description: Messaging stack (RabbitMQ)
  sourceRepos:
    - https://github.com/Eliasdb/eDB.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: messaging
    - name: prod # <-- allow prod cluster by name
      namespace: messaging
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
