apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: networking
  namespace: argocd
spec:
  description: Ingress & networking components
  sourceRepos:
    - https://github.com/Eliasdb/eDB.git
    - https://kubernetes.github.io/ingress-nginx
  destinations:
    - server: https://kubernetes.default.svc
      namespace: ingress-nginx-argo
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
