apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-staging
  namespace: argocd
spec:
  project: networking
  source:
    repoURL: https://github.com/Eliasdb/eDB.git
    targetRevision: dev
    path: k8s/platform/networking/ingress/staging
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: default # required field, but resources declare their own namespaces
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
