apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-staging
  namespace: argocd
spec:
  project: networking
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx-argo
  sources:
    # 1) The chart
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.11.2
      helm:
        valueFiles:
          - $values/k8s/platform/networking/ingress-nginx/values-staging.yaml
    # 2) Your repo containing the values file
    - repoURL: https://github.com/Eliasdb/eDB.git
      targetRevision: dev # or the branch you use
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
