deploymentMode: SingleBinary
fullnameOverride: loki

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 20Gi
  extraInitContainers:
    - name: init-fix-perms
      image: busybox:1.36
      command: ['sh', '-c', 'chown -R 10001:10001 /var/loki || true']
      volumeMounts:
        - name: storage
          mountPath: /var/loki

# turn OFF scalable targets
read: { replicas: 0 }
write: { replicas: 0 }
backend: { replicas: 0 }

podSecurityContext:
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  fsGroupChangePolicy: OnRootMismatch

# optional: keep caches off while stabilizing
chunksCache:
  enabled: false
resultsCache:
  enabled: false

service:
  type: ClusterIP
  ports:
    http: 3100

loki:
  auth_enabled: false

  server:
    http_listen_port: 3100

  storage:
    type: filesystem
    bucketNames:
      chunks: chunks
      ruler: ruler

  commonConfig:
    path_prefix: /var/loki
    replication_factor: 1

  schemaConfig:
    configs:
      - from: 2024-01-01
        store: boltdb-shipper
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

  storage_config:
    boltdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/boltdb-cache
    filesystem:
      directory: /var/loki/chunks

  compactor:
    working_directory: /var/loki/compactor
    compaction_interval: 5m
    retention_enabled: true
    delete_request_store: filesystem

  limits_config:
    retention_period: 7d
    allow_structured_metadata: false
