apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meilisearch-prod
  namespace: argocd
spec:
  project: search
  source:
    repoURL: https://github.com/Eliasdb/eDB.git
    targetRevision: main
    path: k8s/platform/search/meilisearch/overlays/prod
  destination:
    name: prod
    namespace: search
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
