#cloud-config
users:
    - name: cicd-runner
      groups: users, admin, docker
      sudo: ALL=(ALL) NOPASSWD:ALL
      shell: /bin/bash
      ssh_authorized_keys:
          - <key>
packages:
    - fail2ban
    - ufw
    - docker.io
    - git
    - curl
    - build-essential
    - libssl-dev
    - jq # For JSON parsing, often used in scripts
    - tar # For extracting tarballs
package_update: true
package_upgrade: true

runcmd:
    # Configure fail2ban for SSH protection
    - printf "[sshd]\nenabled = true\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
    - systemctl enable fail2ban

    # Enable and configure firewall (allow required ports)
    - ufw allow OpenSSH
    - ufw allow 80 # HTTP (if needed)
    - ufw allow 443 # HTTPS (if needed)
    - ufw allow 22 # SSH
    - ufw enable

    # Secure SSH
    - sed -i -e '/^\(#\|\)PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
    - sed -i -e '/^\(#\|\)PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
    - sed -i -e '/^\(#\|\)KbdInteractiveAuthentication/s/^.*$/KbdInteractiveAuthentication no/' /etc/ssh/sshd_config
    - sed -i -e '/^\(#\|\)ChallengeResponseAuthentication/s/^.*$/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config
    - sed -i -e '/^\(#\|\)MaxAuthTries/s/^.*$/MaxAuthTries 2/' /etc/ssh/sshd_config
    - sed -i -e '/^\(#\|\)AllowTcpForwarding/s/^.*$/AllowTcpForwarding no/' /etc/ssh/sshd_config
    - sed -i -e '/^\(#\|\)X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
    - sed -i -e '/^\(#\|\)AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
    - sed -i -e '/^\(#\|\)AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh\/authorized_keys/' /etc/ssh/sshd_config
    - sed -i '$a AllowUsers ci-runner' /etc/ssh/sshd_config

    # Install GitHub Actions Runner
    - mkdir -p /opt/actions-runner
    - curl -o /opt/actions-runner/actions-runner-linux-arm64.tar.gz -L https://github.com/actions/runner/releases/download/v2.321.0/actions-runner-linux-arm64-2.321.0.tar.gz
    - cd /opt/actions-runner && tar xzf actions-runner-linux-arm64.tar.gz
    - /opt/actions-runner/config.sh --url https://github.com/Eliasdb/eDB --token xxxxx --labels cicd-runner --name arm64-runner --unattended --replace
    - /opt/actions-runner/svc.sh install
    - /opt/actions-runner/svc.sh start

    # Add Docker permissions
    - usermod -aG docker cicd-runner
    - systemctl enable docker
    - systemctl start docker

    # Final reboot
    - reboot
