apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -staging
namespace: default
resources:
  - ../../base
patches:
  - path: patch.yaml
images:
  # Let Argo CD Image Updater inject the tag at runtime
  - name: eliasdb/webshop-api
