apiVersion: apps/v1
kind: Deployment
metadata:
    name: keycloak-staging
    labels:
        app: keycloak-staging
spec:
    replicas: 1
    selector:
        matchLabels:
            app: keycloak-staging
    template:
        metadata:
            labels:
                app: keycloak-staging
        spec:
            containers:
                - name: keycloak
                  image: quay.io/keycloak/keycloak:latest
                  command: [
                          '/opt/keycloak/bin/kc.sh',
                          'start',
                          # '--optimized',
                          '--http-enabled=true', # Allow HTTP inside cluster
                          '--http-port=8080', # Use standard HTTP port

                          # "--hostname=https://app.staging.eliasdebock.com/keycloak",
                          '--proxy-headers=xforwarded',
                          '--http-relative-path=/keycloak',
                      ]
                  ports:
                      - containerPort: 8080
                  env:
                      - name: KC_BOOTSTRAP_ADMIN_USERNAME
                        value: 'admin'
                      - name: KC_BOOTSTRAP_ADMIN_PASSWORD
                        value: 'admin'
                      - name: KC_HOSTNAME
                        value: 'https://app.staging.eliasdebock.com/keycloak'
                      # - name: KC_HTTP_RELATIVE_PATH
                      #   value: '/keycloak'

                      # --- 🔽 PostgreSQL integration ---
                      - name: KC_DB
                        value: postgres
                      - name: KC_DB_URL
                        value: jdbc:postgresql://postgres-service-staging:5432/mydatabase
                      - name: KC_DB_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: postgres-secret-staging
                                key: POSTGRES_USER
                      - name: KC_DB_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: postgres-secret-staging
                                key: POSTGRES_PASSWORD
                      - name: POSTGRES_DB
                        valueFrom:
                            secretKeyRef:
                                name: postgres-secret-staging
                                key: POSTGRES_DB
