apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-api
  labels:
    app: admin-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: admin-api
    spec:
      containers:
        - name: admin-api
          image: eliasdb/admin-api:latest # overridden by overlays
          imagePullPolicy: Always
          ports:
            - containerPort: 9102
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: 'http://+:9102'
          resources:
            requests:
              memory: '256Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
