apiVersion: v1
kind: Service
metadata:
    name: edb-nx-admin-service
spec:
    type: LoadBalancer
    selector:
        app: admin-app-dev
    ports:
        - protocol: TCP
          port: 4300
          targetPort: 4300 # Match your admin app container port
