apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack-prod
  namespace: argocd
spec:
  project: observability
  destination:
    name: prod
    namespace: monitoring

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 75.6.1
      helm:
        releaseName: monitoring
        # skipCrds: true # CRDs are included below via SSA
        valueFiles:
          - $values/k8s/platform/observability/prometheus/values-prod.yaml

    - repoURL: https://github.com/Eliasdb/eDB.git
      targetRevision: main # prod follows main
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true

  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .metadata.annotations["kubectl.kubernetes.io/last-applied-configuration"]
