apiVersion: v1
kind: ConfigMap
metadata:
    labels:
        io.kompose.service: backend
    name: backend-cm0
data:
    NODE_ENV: 'production'
    APP_PORT: '9100'
    DATABASE_URL: 'mysql://myappuser:myuserpassword@db:3306/myapp_db'
