apiVersion: apps/v1
kind: Deployment
metadata:
    name: tools-invoices-staging
    labels:
        app: tools-invoices
spec:
    replicas: 1
    selector:
        matchLabels:
            app: tools-invoices
    template:
        metadata:
            labels:
                app: tools-invoices
        spec:
            containers:
                - name: tools-invoices-api
                  image: eliasdb/tools-invoices-api:pr-343-staging
                  ports:
                      - containerPort: 8000
                  env:
                      - name: ENVIRONMENT
                        value: 'staging'
                  volumeMounts:
                      - name: sa-secret
                        mountPath: /app/service-account.json
                        subPath: service-account.json
            volumes:
                - name: sa-secret
                  secret:
                      secretName: tools-invoices-service-account
