apiVersion: v1
kind: Service
metadata:
    name: tools-invoices-staging # updated name for staging
spec:
    selector:
        app: tools-invoices
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8000
    type: ClusterIP
