# meilisearch-deployment-prod.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: meilisearch-prod # renamed for prod
    labels:
        app: meilisearch
spec:
    replicas: 1 # production usually runs ≥ 2 pods; change as needed
    selector:
        matchLabels:
            app: meilisearch
    template:
        metadata:
            labels:
                app: meilisearch
        spec:
            containers:
                - name: meilisearch
                  image: getmeili/meilisearch:v1.8
                  ports:
                      - containerPort: 7700
                  env:
                      - name: MEILI_MASTER_KEY
                        valueFrom:
                            secretKeyRef:
                                name: meilisearch-secret-prod # production secret
                                key: MEILI_MASTER_KEY
