apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
namespace: default
resources:
  - ../../base
patches:
  - path: patch.yaml
images:
  - name: eliasdb/platform-api
    newTag: v2.0.1 # pin prod here (change via PR)
