apiVersion: v1
kind: Service
metadata:
    name: tools-invoices-prod
    labels:
        app: tools-invoices
        environment: production
spec:
    selector:
        app: tools-invoices
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8000
    type: ClusterIP
