apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: frontend-ingress
    namespace: default
    annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
        nginx.ingress.kubernetes.io/backend-protocol: 'HTTP'
        nginx.ingress.kubernetes.io/use-forwarded-headers: 'true'
        cert-manager.io/cluster-issuer: letsencrypt-production
        cert-manager.io/certificate-name: app-tls
        nginx.ingress.kubernetes.io/proxy-set-headers: 'ingress-nginx/custom-headers'

spec:
    ingressClassName: nginx
    rules:
        - host: app.staging.eliasdebock.com
          http:
              paths:
                  - path: /admin
                    pathType: Prefix
                    backend:
                        service:
                            name: admin-app-staging-service
                            port:
                                number: 80

                  - path: /keycloak
                    pathType: Prefix
                    backend:
                        service:
                            name: keycloak-staging
                            port:
                                number: 8080

                  #   - path: /account
                  #     pathType: Prefix
                  #     backend:
                  #         service:
                  #             name: account-ui-staging-service
                  #             port:
                  #                 number: 80

                  # Catch-all for everything else => Main Angular app
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: edb-nx-staging-service
                            port:
                                number: 80
    tls:
        - hosts:
              - app.staging.eliasdebock.com
          secretName: app-tls
