---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: staging-certificate
    namespace: default
spec:
    secretName: staging-tls
    issuerRef:
        name: letsencrypt-production
        kind: ClusterIssuer
    commonName: app.staging.eliasdebock.com
    dnsNames:
        - app.staging.eliasdebock.com
        - api.staging.eliasdebock.com
