apiVersion: apps/v1
kind: Deployment
metadata:
    name: keycloak-prod
    labels:
        app: keycloak-prod
spec:
    replicas: 1
    selector:
        matchLabels:
            app: keycloak-prod
    template:
        metadata:
            labels:
                app: keycloak-prod
        spec:
            containers:
                - name: keycloak
                  image: quay.io/keycloak/keycloak:latest
                  command: [
                          '/opt/keycloak/bin/kc.sh',
                          'start',
                          '--http-enabled=true', # Allow HTTP inside cluster
                          '--http-port=8080', # Use standard HTTP port
                          '--hostname-strict=false',
                          '--proxy-headers=xforwarded',
                      ]
                  ports:
                      - containerPort: 8080
                  env:
                      - name: KC_BOOTSTRAP_ADMIN_USERNAME
                        value: 'admin'
                      - name: KC_BOOTSTRAP_ADMIN_PASSWORD
                        value: 'admin'
                      - name: KC_HOSTNAME
                        value: 'app.eliasdebock.com' # Set it to match the main domain
                      - name: KC_HTTP_RELATIVE_PATH
                        value: '/keycloak'
