apiVersion: apps/v1
kind: Deployment
metadata:
    name: keycloak-prod
    labels:
        app: keycloak-prod
spec:
    replicas: 1
    selector:
        matchLabels:
            app: keycloak-prod
    template:
        metadata:
            labels:
                app: keycloak-prod
        spec:
            # imagePullSecrets:
            #   - name: dockerhub-creds
            containers:
                - name: keycloak
                  image: eliasdb/keycloak-edb:26.2.4-v19
                  imagePullPolicy: Always

                  ports:
                      - containerPort: 8080

                  env:
                      # bootstrap admin
                      - name: KC_BOOTSTRAP_ADMIN_USERNAME
                        value: 'admin'
                      - name: KC_BOOTSTRAP_ADMIN_PASSWORD
                        value: 'admin'

                      # public URL where users reach Keycloak
                      - name: KC_HOSTNAME
                        value: 'https://app.eliasdebock.com/keycloak'

                      # make your theme the default login UI
                      - name: KC_SPI_THEME_LOGIN_DEFAULT
                        value: 'edb-theme'
                      # you can uncomment these if you want the theme everywhere
                      # - name: KC_SPI_THEME_ACCOUNT_DEFAULT
                      #   value: "edb-theme"
                      # - name: KC_SPI_THEME_ADMIN_DEFAULT
                      #   value: "edb-theme"
                      # - name: KC_SPI_THEME_EMAIL_DEFAULT
                      #   value: "edb-theme"

                      # ---------- Postgres (production) ----------
                      - name: KC_DB
                        value: 'postgres'
                      - name: KC_DB_URL
                        value: 'jdbc:postgresql://postgres-service-prod:5432/mydatabase'
                      - name: KC_DB_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: postgres-secret-prod
                                key: POSTGRES_USER
                      - name: KC_DB_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: postgres-secret-prod
                                key: POSTGRES_PASSWORD
                      - name: POSTGRES_DB
                        valueFrom:
                            secretKeyRef:
                                name: postgres-secret-prod
                                key: POSTGRES_DB
