apiVersion: apps/v1
kind: Deployment
metadata:
    name: platform-app-dev
    namespace: default
    labels:
        app: platform-app-dev
spec:
    replicas: 1
    selector:
        matchLabels:
            app: platform-app-dev
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: platform-app-dev
        spec:
            containers:
                - name: platform-app-dev
                  image: platform-app-dev # Updated image name
                  ports:
                      - containerPort: 4200 # Match with Angular's development port
                        protocol: TCP
                  env:
                      - name: NODE_ENV
                        value: development
                  readinessProbe:
                      httpGet:
                          path: /
                          port: 4200
                      initialDelaySeconds: 5
                      periodSeconds: 10
                      timeoutSeconds: 5
                      failureThreshold: 3
                  livenessProbe:
                      httpGet:
                          path: /
                          port: 4200
                      initialDelaySeconds: 15
                      periodSeconds: 20
                      timeoutSeconds: 5
                      failureThreshold: 3
