---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webshop-api-prod
  namespace: default
  labels:
    app: webshop-api-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webshop-api-prod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webshop-api-prod
    spec:
      containers:
        - name: webshop-api
          image: eliasdb/webshop-api:v1.825
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            # ── Laravel / application ─────────────────────────
            - name: APP_ENV
              value: 'production'
            - name: APP_DEBUG
              value: 'false'
            - name: APP_URL
              value: 'https://api.eliasdebock.com'

            # ── PostgreSQL ────────────────────────────────────
            - name: DB_CONNECTION
              value: 'pgsql'
            - name: DB_HOST
              value: 'postgres-service-prod'
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-prod
                  key: POSTGRES_USER
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-prod
                  key: WEBSHOP_DB
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-prod
                  key: POSTGRES_PASSWORD

            # ── Auth / Keycloak ───────────────────────────────
            - name: KEYCLOAK_JWKS_URL
              value: 'https://app.eliasdebock.com/keycloak/realms/EDB-PROD/protocol/openid-connect/certs'

            # ── NEW: external services secrets ────────────────
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: meilisearch-secret-prod
                  key: MEILI_MASTER_KEY

            - name: MEILISEARCH_KEY
              valueFrom:
                secretKeyRef:
                  name: meilisearch-secret-prod
                  key: MEILI_MASTER_KEY

            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret-prod
                  key: OPENAI_API_KEY
            - name: STRIPE_PUBLIC
              valueFrom:
                secretKeyRef:
                  name: stripe-secret-prod
                  key: STRIPE_PUBLIC
            - name: STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: stripe-secret-prod
                  key: STRIPE_SECRET
          envFrom:
            - secretRef:
                name: webshop-amqp

          resources:
            requests:
              memory: '256Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
