# Use the official .NET SDK image
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

# Set the working directory
WORKDIR /app

# Copy the .csproj and restore dependencies
COPY *.csproj ./
RUN dotnet restore

# Copy the rest of the application code
COPY . ./

# Expose the application port
EXPOSE 9101

# Run the application with dotnet watch for hot reloading
ENTRYPOINT ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:9101"]
