# .github/workflows/admin-ci.yml
name: Admin CI

on:
    workflow_call:
        inputs:
            sha:
                required: true
                type: string
        secrets:
            DOCKER_USERNAME:
                required: true
            DOCKER_TOKEN:
                required: true

jobs:
    build-admin:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  ref: ${{ inputs.sha }}

            - uses: actions/setup-node@v3
              with:
                  node-version: '20'

            - uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: '8.0'

            - run: npm install -g pnpm
            - run: pnpm install
              working-directory: ./eDB

            - name: Build eDB-admin
              working-directory: ./eDB
              run: |
                  pnpm nx build eDB-admin --configuration=staging \
                    --base-href=/admin/ --deploy-url=/admin/

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Docker build & push
              working-directory: ./eDB
              run: |
                  TAG=admin-${{ inputs.sha }}
                  docker build --platform linux/arm64 \
                    -f docker/eDB-admin/Dockerfile.staging \
                    -t eliasdb/edb-admin:$TAG .
                  docker push eliasdb/edb-admin:$TAG
