# .github/workflows/admin-ci.production.yml
name: (Production) Admin App CI

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
        required: true

jobs:
  # ─────────────────────────────────────────────
  lint:
    name: Lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'
      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile
      - name: Lint mfe-edb-admin
        run: pnpm nx lint mfe-edb-admin

  # ─────────────────────────────────────────────
  test:
    name: Test
    runs-on: self-hosted
    needs: lint
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'
      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile
      - name: Test mfe-edb-admin
        run: pnpm nx test mfe-edb-admin --passWithNoTests

  # ─────────────────────────────────────────────
  build:
    name: Build & Push Docker Image
    runs-on: self-hosted
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'
      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile
      - name: Build Admin App
        run: |
          pnpm nx build mfe-edb-admin \
            --configuration=production \
            --base-href=/admin \
            --deploy-url=/admin/
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Docker build & push
        run: |
          TAG=${{ inputs.image_tag }}
          echo "📦 Building & pushing admin image:$TAG"
          docker build --platform linux/arm64 \
            -f docker/mfe-edb-admin/Dockerfile.prod \
            -t eliasdb/edb-admin:$TAG .
          docker push eliasdb/edb-admin:$TAG
