name: CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        name: Build, Push, and Deploy
        runs-on: ubuntu-latest

        env:
            DOCKER_IMAGE_API: eliasdb/edb-api
            DOCKER_IMAGE_FRONTEND: eliasdb/edb-nx

        steps:
            # Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v3

            # Log in to Docker Hub
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            # Build API Docker image
            - name: Build API Docker image
              run: |
                  docker build -t $DOCKER_IMAGE_API:latest -t $DOCKER_IMAGE_API:${{ github.sha }} -f ./api/Dockerfile.prod ./api

            # Build Frontend Docker image
            - name: Build Frontend Docker image
              run: |
                  docker build -t $DOCKER_IMAGE_FRONTEND:latest -t $DOCKER_IMAGE_FRONTEND:${{ github.sha }} -f ./eDB/Dockerfile.prod ./eDB

            # Push API Docker image
            - name: Push API Docker image
              run: |
                  docker push $DOCKER_IMAGE_API:latest
                  docker push $DOCKER_IMAGE_API:${{ github.sha }}

            # Push Frontend Docker image
            - name: Push Frontend Docker image
              run: |
                  docker push $DOCKER_IMAGE_FRONTEND:latest
                  docker push $DOCKER_IMAGE_FRONTEND:${{ github.sha }}

            # Set up kubectl
            - name: Set up kubectl
              uses: azure/setup-kubectl@v3
              with:
                  version: 'latest'

            # Configure Kubernetes
            - name: Configure Kubernetes
              run: |
                  echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
                  export KUBECONFIG=kubeconfig
                  kubectl cluster-info

            # Deploy API to Kubernetes
            - name: Deploy API to Kubernetes
              run: |
                  kubectl set image deployment/api-prod api=$DOCKER_IMAGE_API:${{ github.sha }}
                  kubectl rollout status deployment/api-prod

            # Deploy Frontend to Kubernetes
            - name: Deploy Frontend to Kubernetes
              run: |
                  kubectl set image deployment/edb-nx-prod edb-nx=$DOCKER_IMAGE_FRONTEND:${{ github.sha }}
                  kubectl rollout status deployment/edb-nx-prod
