name: CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        name: Build, Push, Validate, and Deploy
        runs-on: ubuntu-latest

        # Only run this job if the commit is not made by the GitHub Actions bot
        if: github.actor != 'github-actions[bot]'

        steps:
            # 0. Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v3

            # 1. Set Version (Automated Version Incrementation)
            - name: Set Version
              id: version
              run: |
                  # Fetch the total number of commits
                  COMMIT_COUNT=$(git rev-list --count HEAD)
                  # Define the version based on commit count
                  VERSION=v1.0.${COMMIT_COUNT}-prod
                  # Export IMAGE_TAG as an environment variable
                  echo "IMAGE_TAG=${VERSION}" >> $GITHUB_ENV

            # 2. Log in to Docker Hub
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            # 3. Build and Push API Docker image with gha cache
            - name: Build and Push API Docker image
              uses: docker/build-push-action@v3
              with:
                  context: ./api
                  file: ./api/Dockerfile.prod
                  push: true
                  tags: |
                      $DOCKER_IMAGE_API:latest
                      $DOCKER_IMAGE_API:${{ env.IMAGE_TAG }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            # 4. Build and Push Frontend Docker image with gha cache
            - name: Build and Push Frontend Docker image
              uses: docker/build-push-action@v3
              with:
                  context: ./eDB
                  file: ./eDB/Dockerfile.prod
                  push: true
                  tags: |
                      $DOCKER_IMAGE_FRONTEND:latest
                      $DOCKER_IMAGE_FRONTend:${{ env.IMAGE_TAG }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            # 5. Set up kubectl
            - name: Set up kubectl
              uses: azure/setup-kubectl@v3
              with:
                  version: 'latest'

            # 6. Configure Kubernetes
            - name: Configure Kubernetes
              run: |
                  mkdir -p ~/.kube
                  echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ~/.kube/config
                  chmod 600 ~/.kube/config
                  kubectl cluster-info

            # 7. Lint YAML Files
            - name: Lint YAML Files
              run: |
                  sudo apt-get update
                  sudo apt-get install -y yamllint
                  yamllint k8s/prod/api/api-deployment.prod.yaml
                  yamllint k8s/prod/eDB/frontend-deployment.prod.yaml

            # 8. Replace Placeholder with Image Tag for API Deployment
            - name: Update API Deployment YAML with Image Tag
              run: |
                  sed "s/\${IMAGE_TAG}/${{ env.IMAGE_TAG }}/g" k8s/prod/api/api-deployment-template.prod.yaml > k8s/prod/api/api-deployment.prod.yaml

            # 9. Replace Placeholder with Image Tag for Frontend Deployment
            - name: Update Frontend Deployment YAML with Image Tag
              run: |
                  sed "s/\${IMAGE_TAG}/${{ env.IMAGE_TAG }}/g" k8s/prod/eDB/frontend-deployment-template.prod.yaml > k8s/prod/eDB/frontend-deployment.prod.yaml

            # 10. Validate API Deployment YAML
            - name: Validate API Deployment YAML
              run: |
                  kubectl apply --dry-run=client -f k8s/prod/api/api-deployment.prod.yaml

            # 11. Validate Frontend Deployment YAML
            - name: Validate Frontend Deployment YAML
              run: |
                  kubectl apply --dry-run=client -f k8s/prod/eDB/frontend-deployment.prod.yaml

            # 12. Deploy API to Kubernetes with Rollback
            - name: Deploy API to Kubernetes
              run: |
                  kubectl apply -f k8s/prod/api/api-deployment.prod.yaml
                  kubectl rollout status deployment/api-prod || kubectl rollout undo deployment/api-prod

            # 13. Deploy Frontend to Kubernetes with Rollback
            - name: Deploy Frontend to Kubernetes
              run: |
                  kubectl apply -f k8s/prod/eDB/frontend-deployment.prod.yaml
                  kubectl rollout status deployment/edb-nx-prod || kubectl rollout undo deployment/edb-nx-prod

            # 14. Commit Updated API Deployment YAML
            - name: Commit API Deployment YAML
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git add k8s/prod/api/api-deployment.prod.yaml
                  git commit -m "Update API deployment to ${{ env.IMAGE_TAG }}" || echo "No changes to commit"

            # 15. Commit Updated Frontend Deployment YAML
            - name: Commit Frontend Deployment YAML
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git add k8s/prod/eDB/frontend-deployment.prod.yaml
                  git commit -m "Update Frontend deployment to ${{ env.IMAGE_TAG }}" || echo "No changes to commit"

            # 16. Push Changes to GitHub
            - name: Push Changes
              uses: ad-m/github-push-action@v0.6.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: main

        # Define environment variables
        env:
            DOCKER_IMAGE_API: eliasdb/edb-api
            DOCKER_IMAGE_FRONTEND: eliasdb/edb-nx
