name: CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        name: Build, Push, and Deploy
        runs-on: ubuntu-latest

        env:
            DOCKER_IMAGE_API: eliasdb/edb-api
            DOCKER_IMAGE_FRONTEND: eliasdb/edb-nx
            IMAGE_TAG: ${{ github.sha }} # Define IMAGE_TAG as the commit SHA

        steps:
            # 1. Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v3

            # 2. Log in to Docker Hub
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            # 3. Build API Docker image
            - name: Build API Docker image
              run: |
                  docker build -t $DOCKER_IMAGE_API:latest -t $DOCKER_IMAGE_API:${IMAGE_TAG} -f ./api/Dockerfile.prod ./api

            # 4. Push API Docker image
            - name: Push API Docker image
              run: |
                  # docker push $DOCKER_IMAGE_API:latest
                  docker push $DOCKER_IMAGE_API:${IMAGE_TAG}

            # 5. Build Frontend Docker image
            - name: Build Frontend Docker image
              run: |
                  docker build -t $DOCKER_IMAGE_FRONTEND:latest -t $DOCKER_IMAGE_FRONTEND:${IMAGE_TAG} -f ./eDB/Dockerfile.prod ./eDB

            # 6. Push Frontend Docker image
            - name: Push Frontend Docker image
              run: |
                  # docker push $DOCKER_IMAGE_FRONTEND:latest
                  docker push $DOCKER_IMAGE_FRONTEND:${IMAGE_TAG}

            # 7. Set up kubectl
            - name: Set up kubectl
              uses: azure/setup-kubectl@v3
              with:
                  version: 'latest'

            # 8. Configure Kubernetes
            - name: Configure Kubernetes
              run: |
                  mkdir -p ~/.kube
                  echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ~/.kube/config
                  chmod 600 ~/.kube/config
                  kubectl cluster-info

            # 9. Replace Placeholder with Commit SHA for API Deployment
            - name: Update API Deployment YAML with Image Tag
              run: |
                  sed "s/\${IMAGE_TAG}/${{ github.sha }}/g" k8s/prod/api/api-deployment-template.prod.yaml > k8s/prod/api/api-deployment.prod.yaml

            # 10. Replace Placeholder with Commit SHA for Frontend Deployment
            - name: Update Frontend Deployment YAML with Image Tag
              run: |
                  sed "s/\${IMAGE_TAG}/${{ github.sha }}/g" k8s/prod/eDB/frontend-deployment-template.prod.yaml > k8s/prod/eDB/frontend-deployment.prod.yaml

            # 11. Apply API Deployment
            - name: Deploy API to Kubernetes
              run: |
                  kubectl apply -f k8s/prod/api-deployment.prod.yaml
                  kubectl rollout status deployment/api-prod

            # 12. Apply Frontend Deployment
            - name: Deploy Frontend to Kubernetes
              run: |
                  kubectl apply -f k8s/prod/frontend-deployment.prod.yaml
                  kubectl rollout status deployment/edb-nx-prod
