name: CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        name: Build, Push, Validate, and Deploy
        runs-on: ubuntu-latest

        # Only run this job if the commit is not made by the GitHub Actions bot
        if: github.actor != 'github-actions[bot]'

        steps:
            # 0. Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v3

            # 1. Set Version (Automated Version Incrementation)
            - name: Set Version
              id: version
              run: |
                  # Fetch the total number of commits
                  COMMIT_COUNT=$(git rev-list --count HEAD)
                  # Define the version based on commit count
                  VERSION=v1.0.${COMMIT_COUNT}-prod
                  # Export IMAGE_TAG as an environment variable
                  echo "IMAGE_TAG=${VERSION}" >> $GITHUB_ENV

            # 2. Log in to Docker Hub
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            # 3. Cache Docker layers
            - name: Cache Docker layers
              uses: actions/cache@v3
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-buildx-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-

            # 4. Build API Docker image
            - name: Build API Docker image
              run: |
                  docker build --cache-from=type=local,src=/tmp/.buildx-cache \
                               --cache-to=type=local,dest=/tmp/.buildx-cache-new \
                               -t $DOCKER_IMAGE_API:latest \
                               -t $DOCKER_IMAGE_API:${{ env.IMAGE_TAG }} \
                               -f ./api/Dockerfile.prod ./api

            # 5. Push API Docker image
            - name: Push API Docker image
              run: |
                  # docker push $DOCKER_IMAGE_API:latest
                  docker push $DOCKER_IMAGE_API:${{ env.IMAGE_TAG }}

            # 6. Build Frontend Docker image
            - name: Build Frontend Docker image
              run: |
                  docker build --cache-from=type=local,src=/tmp/.buildx-cache \
                               --cache-to=type=local,dest=/tmp/.buildx-cache-new \
                               -t $DOCKER_IMAGE_FRONTEND:latest \
                               -t $DOCKER_IMAGE_FRONTEND:${{ env.IMAGE_TAG }} \
                               -f ./eDB/Dockerfile.prod ./eDB

            # 7. Push Frontend Docker image
            - name: Push Frontend Docker image
              run: |
                  # docker push $DOCKER_IMAGE_FRONTEND:latest
                  docker push $DOCKER_IMAGE_FRONTEND:${{ env.IMAGE_TAG }}

            # 8. Set up kubectl
            - name: Set up kubectl
              uses: azure/setup-kubectl@v3
              with:
                  version: 'latest'

            # 9. Configure Kubernetes
            - name: Configure Kubernetes
              run: |
                  mkdir -p ~/.kube
                  echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ~/.kube/config
                  chmod 600 ~/.kube/config
                  kubectl cluster-info

            # 10. Lint YAML Files
            - name: Lint YAML Files
              run: |
                  sudo apt-get update
                  sudo apt-get install -y yamllint
                  yamllint k8s/prod/api/api-deployment.prod.yaml
                  yamllint k8s/prod/eDB/frontend-deployment.prod.yaml

            # 11. Replace Placeholder with Image Tag for API Deployment
            - name: Update API Deployment YAML with Image Tag
              run: |
                  sed "s/\${IMAGE_TAG}/${{ env.IMAGE_TAG }}/g" k8s/prod/api/api-deployment-template.prod.yaml > k8s/prod/api/api-deployment.prod.yaml

            # 12. Replace Placeholder with Image Tag for Frontend Deployment
            - name: Update Frontend Deployment YAML with Image Tag
              run: |
                  sed "s/\${IMAGE_TAG}/${{ env.IMAGE_TAG }}/g" k8s/prod/eDB/frontend-deployment-template.prod.yaml > k8s/prod/eDB/frontend-deployment.prod.yaml

            # 13. Validate API Deployment YAML
            - name: Validate API Deployment YAML
              run: |
                  kubectl apply --dry-run=client -f k8s/prod/api/api-deployment.prod.yaml

            # 14. Validate Frontend Deployment YAML
            - name: Validate Frontend Deployment YAML
              run: |
                  kubectl apply --dry-run=client -f k8s/prod/eDB/frontend-deployment.prod.yaml

            # 15. Deploy API to Kubernetes with Rollback
            - name: Deploy API to Kubernetes
              run: |
                  kubectl apply -f k8s/prod/api/api-deployment.prod.yaml
                  kubectl rollout status deployment/api-prod || kubectl rollout undo deployment/api-prod

            # 16. Deploy Frontend to Kubernetes with Rollback
            - name: Deploy Frontend to Kubernetes
              run: |
                  kubectl apply -f k8s/prod/eDB/frontend-deployment.prod.yaml
                  kubectl rollout status deployment/edb-nx-prod || kubectl rollout undo deployment/edb-nx-prod

            # 17. Commit Updated API Deployment YAML
            - name: Commit API Deployment YAML
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git add k8s/prod/api/api-deployment.prod.yaml
                  git commit -m "Update API deployment to ${{ env.IMAGE_TAG }}" || echo "No changes to commit"

            # 18. Commit Updated Frontend Deployment YAML
            - name: Commit Frontend Deployment YAML
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git add k8s/prod/eDB/frontend-deployment.prod.yaml
                  git commit -m "Update Frontend deployment to ${{ env.IMAGE_TAG }}" || echo "No changes to commit"

            # 19. Push Changes to GitHub
            - name: Push Changes
              uses: ad-m/github-push-action@v0.6.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: main

        # Define environment variables
        env:
            DOCKER_IMAGE_API: eliasdb/edb-api
            DOCKER_IMAGE_FRONTEND: eliasdb/edb-nx
