name: Deploy to Staging

on:
    push:
        branches:
            - dev

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Deploy to Staging
              run: ./deploy-to-staging.sh # Your deployment script

    e2e-tests:
        needs: deploy
        runs-on: ubuntu-latest

        steps:
            - name: Run E2E Tests
              run: npm run e2e # Cypress, Playwright, or Selenium tests
