name: Development Workflow

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - main

jobs:
  lint:
      name: Lint Code
      runs-on: ubuntu-latest
      steps:
          - name: Checkout Code
            uses: actions/checkout@v3
          - name: Setup Node.js
            uses: actions/setup-node@v3
            with:
                node-version: '20'
          - name: Install Dependencies
            run: pnpm install
            working-directory: ./eDB/eDB # Set the path to where package.json is located
          - name: Run Lint for All Projects
            run: pnpm nx run-many --target=lint --all || true
            working-directory: ./eDB/eDB # Adjust as needed

    test:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'
            - name: Install pnpm
              run: corepack enable && corepack prepare pnpm@latest --activate
            - name: Install Dependencies
              run: pnpm install
            - name: Run Tests
              run: pnpm nx run-many --target=test --all --exclude=appointment-app

    build-backend:
        name: Build Backend
        runs-on: ubuntu-latest
        needs: [lint, test]
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Build Backend
              run: dotnet build ./api/api.csproj --configuration Release

    build-frontend:
        name: Build Frontend
        runs-on: ubuntu-latest
        needs: [lint, test]
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Install pnpm
              run: corepack enable && corepack prepare pnpm@latest --activate
            - name: Install Dependencies
              run: pnpm install
            - name: Build Frontend
              run: pnpm build
