name: Pre-Merge Checks Dev Branch

on:
    pull_request:
        branches:
            - dev
        paths:
            - 'api/**'
            - 'eDB/**'

jobs:
    filter:
        name: Check if Backend or Frontend Code Changed
        runs-on: [self-hosted]
        outputs:
            backend: ${{ steps.set_backend.outputs.backend }}
            frontend: ${{ steps.set_frontend.outputs.frontend }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2

            - name: Set Backend Changed
              id: set_backend
              run: |
                  if git diff --name-only HEAD~1 HEAD | grep -q '^api/'; then
                    echo "backend=true" >> $GITHUB_OUTPUT
                  else
                    echo "backend=false" >> $GITHUB_OUTPUT
                  fi
              shell: bash

            - name: Set Frontend Changed
              id: set_frontend
              run: |
                  if git diff --name-only HEAD~1 HEAD | grep -q '^eDB/'; then
                    echo "frontend=true" >> $GITHUB_OUTPUT
                  else
                    echo "frontend=false" >> $GITHUB_OUTPUT
                  fi
              shell: bash

            - name: Debug Filter Outputs
              run: |
                  echo "Backend changed: ${{ steps.set_backend.outputs.backend }}"
                  echo "Frontend changed: ${{ steps.set_frontend.outputs.frontend }}"

    version:
        name: Set Version
        runs-on: [self-hosted]
        needs: filter
        outputs:
            image_tag: ${{ steps.version.outputs.image_tag }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Set Version with PR Number
              id: version
              run: |
                  PR_NUMBER=${{ github.event.pull_request.number }}
                  VERSION=pr-${PR_NUMBER}-staging
                  echo "image_tag=${VERSION}" >> $GITHUB_ENV
                  echo "image_tag=${VERSION}" >> $GITHUB_OUTPUT

    lint:
        name: Lint Frontend Code
        runs-on: [self-hosted]
        needs: [filter, version]
        if: ${{ needs.filter.outputs.frontend == 'true' }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'

            - name: Install pnpm
              run: corepack enable && corepack prepare pnpm@latest --activate

            - name: Install Dependencies
              run: pnpm install
              working-directory: ./eDB

            - name: Run Lint for All Projects
              run: pnpm nx run-many --target=lint --all --verbose || true
              working-directory: ./eDB

    test:
        name: Run Frontend Unit and Integration Tests
        runs-on: [self-hosted]
        needs: [filter, version]
        if: ${{ needs.filter.outputs.frontend == 'true' }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'

            - name: Install pnpm
              run: corepack enable && corepack prepare pnpm@latest --activate

            - name: Install Dependencies
              run: pnpm install
              working-directory: ./eDB

            - name: Run Tests
              run: pnpm nx run-many --target=test --all --exclude=appointment-app --verbose || true
              working-directory: ./eDB

    build-backend:
        name: Build and Push Backend Docker Image
        runs-on: [self-hosted]
        needs: [filter, version]
        if: ${{ needs.filter.outputs.backend == 'true' }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and Push Backend Docker Image
              uses: docker/build-push-action@v3
              with:
                  context: ./api
                  file: ./api/Dockerfile.prod
                  push: true
                  tags: eliasdb/edb-api:${{ needs.version.outputs.image_tag }}
                  platforms: linux/arm64

    build-frontend:
        name: Build and Push Frontend Docker Image
        runs-on: [self-hosted]
        needs: [filter, lint, test, version]
        if: ${{ needs.filter.outputs.frontend == 'true' }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and Push Frontend Docker Image
              uses: docker/build-push-action@v3
              with:
                  context: ./eDB
                  file: ./eDB/Dockerfile.prod
                  push: true
                  tags: eliasdb/edb-nx:${{ needs.version.outputs.image_tag }}
                  platforms: linux/arm64
