---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: web-app-prod
    namespace: default
    labels:
        app: web-app
spec:
    replicas: 1
    selector:
        matchLabels:
            app: web-app
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: web-app
        spec:
            containers:
                - name: web-app
                  image: eliasdb/edb:${IMAGE_TAG}
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
                        protocol: TCP
                  env:
                      - name: NODE_ENV
                        value: production
                  readinessProbe:
                      httpGet:
                          path: /
                          port: 80
                      initialDelaySeconds: 5
                      periodSeconds: 10
                      timeoutSeconds: 5
                      failureThreshold: 3
                  livenessProbe:
                      httpGet:
                          path: /
                          port: 80
                      initialDelaySeconds: 15
                      periodSeconds: 20
                      timeoutSeconds: 5
                      failureThreshold: 3
