apiVersion: v1
kind: Service
metadata:
    name: edb-nx-prod-service
    namespace: default
    labels:
        app: edb-nx
spec:
    type: ClusterIP
    selector:
        app: edb-nx
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
