apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: monitoring-tls
    namespace: monitoring
spec:
    secretName: monitoring-tls
    issuerRef:
        name: letsencrypt-production
        kind: ClusterIssuer
    dnsNames:
        - grafana.staging.eliasdebock.com
