apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: api-tls
    namespace: default
spec:
    secretName: api-tls
    issuerRef:
        name: letsencrypt-production
        kind: ClusterIssuer
    commonName: api.staging.eliasdebock.com
    dnsNames:
        - api.staging.eliasdebock.com
