apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: prometheus-tls
    namespace: monitoring
spec:
    secretName: prometheus-tls
    issuerRef:
        name: letsencrypt-production
        kind: ClusterIssuer
    dnsNames:
        - prometheus.staging.eliasdebock.com
